Fix includes being read twice and not using content provided by possibly overridden TryFindInclude
jpbruyere/shaderc.net pull request #2
Opened 2023-06-20 06:31 UTC by Tacodiva

This library appears to read the content of included files twice, first in `TryFindInclude` then again in `HandlePFN_IncludeResolve`. This PR fixes that. This issue is particularly egregious because it forces anybody overriding `TryFindInclude` into returning a path to a real file  on the local computer, which may not be the case.

2023-06-20 11:33 UTC, jpbruyere commented
But what to do if include is not found? throw error?

2023-06-21 01:31 UTC, Tacodiva commented
Thanks for the quick response :blush:
Right now it does the same thing the old code did, set both the source name and content to empty strings. However, according to [the comment here](https://github.com/google/shaderc/blob/4dc596ddc2702092c670e828745dc3e0338d83c1/libshaderc/include/shaderc/shaderc.h#L341), on an error the source name of the file should be empty but the content can be set to an error message. I've pushed some changes which add a default error message but still allows a custom one from implementations of they override `TryFindInclude`.

2023-06-21 02:45 UTC, jpbruyere requested changes
The default message could be set directly here: https://github.com/jpbruyere/shaderc.net/blob/master/shaderc.net/Options.cs#L89

2023-06-21 03:50 UTC, Tacodiva commented
Okie, moved it

2023-06-21 04:12 UTC, merged

2023-06-21 04:14 UTC, jpbruyere commented
Thank you for this fix.